apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Nginx configuration for reverse proxy
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Nginx configuration for reverse proxy
    server {
      listen 80;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }

      location /api1 {
        #rewrite ^/api1/(.+) /$1 break;
        proxy_pass http://frontendapp-service:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-Prefix /api1;
        proxy_set_header X-Forwarded-Uri $uri;
      }

      location /js {
        proxy_pass http://frontendapp-service:3000/js/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-Prefix /api1;
        proxy_set_header X-Forwarded-Uri $uri;
      } 

      location /api2 {
        rewrite ^/api2/(.+) /$1 break;
        proxy_pass http://productapp-service:8000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-Prefix /api2;
        proxy_set_header X-Forwarded-Uri $uri;
      }

      location /api3 {
        rewrite ^/api3/(.+) /$1 break;
        proxy_pass http://userapp-service:8010/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-Prefix /api3;
        proxy_set_header X-Forwarded-Uri $uri; 
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <h1>Hello, ArgoCD!! Hello, GitOps!!</h1>
