# Default values for hellomsa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

frontendapp:
  image: "siestageek/frontendapp" # Replace with your actual image name
  tag: latest
  port: 3000

productapp:
  image: "siestageek/productapp" # Replace with your actual image name
  tag: latest
  port: 8000

userapp:
  image: "siestageek/userapp" # Replace with your actual image name
  tag: latest
  port: 8010

nginx:
  image: nginx:latest
  tag: latest

